### ISSUE TITLE
possible test failure in upcoming Julia version 1.5

### ISSUE THREAD

**Issue by rfourquet** [JeffFessler/MIRT.jl#41]
A PkgEval run for a [PR](https://github.com/JuliaLang/julia/pull/35078) which changes the generated numbers for `randn!` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master). Apologies if this is a false positive.
cf. https://github.com/JuliaCI/NanosoldierReports/blob/7de24e455342298cbef56826b5827f0d7640d2c1/pkgeval/by_hash/b89e35c_vs_098ef24/logs/MIRT/1.5.0-DEV-71a4a114c2.log

**Comment by JeffFessler** [comment]
Thanks for alerting me.  It turns out that I had a tolerance that was too small there, so I have changed it to use isapprox and I suspect it will be fine now.  It passes Julia 1.4 tests.  I tried to test 1.5 on TravisCI but I guess they are not yet supporting 1.5.  So I downloaded the latest nightly build of 1.5 and tested it locally and it passed.
It's wonderful that the Julia community has these tools that help us be proactive!  Thanks!

**Comment by rfourquet** [comment]
You're welcome! Actually the PR was merged just before opening the issue, so I guess the "latest nightly build" doesn't contain yet the change. But yes, using `isapprox` will probably be enough (but the change also broke some tests which had `isapprox`).

**Comment by JeffFessler** [comment]
I tested with a newer nightly and it passed, after fixing some other new issues.  Thanks again.
